
MongoURI: "mongodb+srv://shrigorevich:456385@cluster0.kjaby.azure.mongodb.net/jeroniya?retryWrites=true&w=majority"


# Множитель суммы опыта, необходимого для повышения уровня
EXP_TO_LVL_UP_CF: 1.5

# MINER JOB
# EXPERIENCE FOR ORE MINING
COAL_ORE_EXP: 10
REDSTONE_ORE_EXP: 10
IRON_ORE_EXP: 20
LAPIS_ORE_EXP: 20
GOLD_ORE_EXP: 40
EMERALD_ORE_EXP: 40
DIAMOND_ORE_EXP: 150

# WOODCUTTER JOB
#EXPERIENCE FOR CUTTING WOOD
LOG_EXP: 20
WOOD_EXP: 5

#FARMER JOB
#EXPERIENCE FOR HARVESTING
CROPS_EXP: 10 #ПШЕНИЦА
SUGAR_CANE_BLOCK_EXP: 10 #ТРОСТНИК
POTATO_EXP: 10 #КАРТОФЕЛЬ
CARROT_EXP: 10 #МОРКОВЬ
PUMPKIN_EXP: 20 #ТЫКВА
MELON_BLOCK_EXP: 20 #АРБУЗ