
# ПОСТОЯННАЯ ОПЫТА: кол-во опыта, необходимого для первого повышения
EXP_CONST: 200
# DROP CHANCE PER LVL (%)
CHANCE_PER_LVL: 7
# CHANCE FOR EXTRA SEEDS (%)
EXTRA_SEEDS_CHANCE: 40
# DAMAGE PER LVL FOR HUNTERS
DAMAGE_PER_LVL: 0.5

# MINER JOB
# EXPERIENCE FOR ORE MINING
COAL_ORE_EXP: 10
REDSTONE_ORE_EXP: 10
IRON_ORE_EXP: 20
LAPIS_ORE_EXP: 20
GOLD_ORE_EXP: 40
EMERALD_ORE_EXP: 40
DIAMOND_ORE_EXP: 150

# WOODCUTTER JOB
# EXPERIENCE FOR CUTTING WOOD
LOG_EXP: 20

# FARMER JOB
# EXPERIENCE FOR HARVESTING
CROPS_EXP: 10 #ПШЕНИЦА
SUGAR_CANE_BLOCK_EXP: 10 #ТРОСТНИК
POTATO_EXP: 10 #КАРТОФЕЛЬ
CARROT_EXP: 10 #МОРКОВЬ
PUMPKIN_EXP: 20 #ТЫКВА
MELON_BLOCK_EXP: 20 #АРБУЗ

# BREEDER JOB
# EXPERIENCE FOR KILLING ANIMALS
COW_EXP: 40
CHICKEN_EXP: 30
PIG_EXP: 30
SHEEP_EXP: 30
HORSE_EXP: 100
SHEAR_EXP: 40 # EXPERIENCE FOR SHEEPSHEARING (стрижка овец)
# EXPERIENCE FOR BREEDING
COW_BREEDING_EXP: 40
CHICKEN_BREEDING_EXP: 30
PIG_BREEDING_EXP: 30
SHEEP_BREEDING_EXP: 30
HORSE_BREEDING_EXP: 100
SHEAR_BREEDING_EXP: 40

# HUNTER JOB
# EXPERIENCE FOR EMEMIES
CREEPER_EXP: 20
ZOMBIE_EXP: 20
SKELETON_EXP: 20
WITCH_EXP: 40
PLAYER_EXP: 100
SPIDER_EXP: 20
CAVE_SPIDER_EXP: 30
ENDERMAN_EXP: 80

# DATABASE STRING CONNECTION (DO NOT CHANGE)
MongoURI: mongodb+srv://shrigorevich:456385@cluster0.kjaby.azure.mongodb.net/jeroniya?retryWrites=true&w=majority